создание массивов

In [17]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("Массив из списка: ", arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Двумерный массив: ")
print(arr2)

ones = np.ones((2, 3, 4))
print("Трехмерный массив 2x3x4, состоящий из единиц: ")
print(ones)

zeros = np.zeros(5)
print("Массив из нулей: ", zeros)

identity = np.eye(5)
print("Единичная матрица 5x5: ")
print(identity)

range_arr = np.arange(0, 10, 2)
print("Массив от 0 до 10 (не включительно) с шагом 2: ", range_arr)

random_arr = np.random.randint(0, 11, (3, 4))
print("Матрица 3x4, состоящая из целых случайных чисел от 0 до 10: ")
print(random_arr)

random_int = np.random.sample(5)
print("Массив, состоящий из пяти случайных чисел: ", random_int)

Массив из списка:  [1 2 3 4 5]
Двумерный массив: 
[[1 2 3]
 [4 5 6]]
Трехмерный массив 2x3x4, состоящий из единиц: 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Массив из нулей:  [0. 0. 0. 0. 0.]
Единичная матрица 5x5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Массив от 0 до 10 (не включительно) с шагом 2:  [0 2 4 6 8]
Матрица 2x3, состоящая из случайных чисел: 
[[1 1 1 0]
 [2 1 1 1]
 [0 1 0 1]]
Массив, состоящий из пяти случайных чисел:  [0.23357587 0.02070278 0.05910792 0.49569927 0.27760724]


индексирование и срезы

In [29]:
import numpy as np

# тестовые массивы
arr_1d = np.array([10, 20, 30, 40, 50, 60])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Массив: ", arr_1d)
print("Двумерный массив: ")
print(arr_2d)

# Индексирование
print("Первый элемент: ", arr_1d[0])
print("Последний элемент: ", arr_1d[-1])
print("Третий элемент: ", arr_1d[2])

print("Правый нижний элемент двумерного массива: ", arr_2d[2,2])

# Срезы
print("Элементы с 1 по 3: ", arr_1d[1:4])
print("Каждый второй элемент: ", arr_1d[::2])
print("Обратный порядок: ", arr_1d[::-1])

print("Кусок двумерного массива (по строкам) : ")
print(arr_2d[[1,2]])
print("Третий столбец куска двумерного массива: ")
print(arr_2d[[1,2], 2])
print("Кусок двумерного массива по интервалам: ")
print(arr_2d[0:2,0:2])
print("Строка двумерного массива : ")
print(arr_2d[2])

Массив:  [10 20 30 40 50 60]
Двумерный массив: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Первый элемент:  10
Последний элемент:  60
Третий элемент:  30
Правый нижний элемент двумерного массива:  9
Элементы с 1 по 3:  [20 30 40]
Каждый второй элемент:  [10 30 50]
Обратный порядок:  [60 50 40 30 20 10]
Кусок двумерного массива (по строкам) : 
[[4 5 6]
 [7 8 9]]
Третий столбец куска двумерного массива: 
[6 9]
Кусок двумерного массива по интервалам: 
[[1 2]
 [4 5]]
Строка двумерного массива : 
[7 8 9]


простые операции

In [35]:
a = np.array([10, 13, 7, 18, 33]) 
b = np.arange(5) # [0, 1, 2, 3, 4]
с=a+b
print("Сумма: ", с)
с=a - b
print("Разность: ", с)
с=a*b
print("Произведение: ", с)
с=a/b
print("Частное: ", с)
a + 1
print("+1 к массиву a: ", a)

Сумма:  [10 14  9 21 37]
Разность:  [10 12  5 15 29]
Произведение:  [  0  13  14  54 132]
Частное:  [  inf 13.    3.5   6.    8.25]
+1 к массиву a:  [10 13  7 18 33]


/var/folders/ky/9pp9rlmx6dvggkfjdtlh3c140000gn/T/ipykernel_3735/3769376374.py:9: RuntimeWarning: divide by zero encountered in divide
  с=a/b


статистики

In [2]:
print ('ggg')


ggg
